controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_base_joint"]
    right_wheel_names: ["right_wheel_base_joint"]

    wheel_separation: 0.25 # 2(radius - wheel_length)
    wheel_radius: 0.034

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

    position_feedback: false
    use_stamped_vel: false
