<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="base_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${chassis_length*1/2} 0 0"/>
    </joint>

    <joint name="left_wheel_base_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${chassis_width/2 + wheel_length/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="right_wheel_base_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${chassis_width/2 + wheel_length/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="caster_wheel_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="-${caster_wheel_base_joint_length} 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="lidar_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar"/>
        <origin xyz="0 0 ${chassis_height + lidar_length/2}" rpy="0 0 ${pi}"/>
    </joint>
    
</robot>