<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Red</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="lidar">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
    
    
            <!-- Wheel Information -->
            <left_joint>left_wheel_base_joint</left_joint>
            <right_joint>right_wheel_base_joint</right_joint>
            <wheel_separation>${chassis_width + wheel_length}</wheel_separation>
            <wheel_diameter>${wheel_radius*2}</wheel_diameter>
    

            <!-- Limits -->
            <max_wheel_torque>200</max_wheel_torque>
            <max_wheel_acceleration>10.0</max_wheel_acceleration>
    

            <!-- Output -->
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
    
    
        </plugin>
    </gazebo>

</robot>