<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <link name="base_link"/>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <xacro:macro name="wheel" params="name *origin">
        <link name="${name}">
            <visual>
                <xacro:insert_block name="origin"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <xacro:insert_block name="origin"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>            
            </collision>
            <xacro:inertial_cylinder mass="0.01" radius="${wheel_radius}" length="${wheel_length}">
                <xacro:insert_block name="origin"/>
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <xacro:wheel name="left_wheel">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:wheel>

    <xacro:wheel name="right_wheel">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:wheel>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/> 
            </geometry>
            <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/> 
            </geometry>
            <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.01" radius="${lidar_radius}" length="${lidar_length}">
            <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder> 
    </link>

</robot>